version: "3.8"
services:
  pubmed-pipeline:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - OUTPUT_DIR=results/
      - HUGGINGFACE_MODELS=dmis-lab/biobert-base-cased-v1.1,allenai/scibert_scivocab_uncased