# environment.yml

name: pubmed-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - biopython
  - pandas
  - tqdm
  - scikit-learn
  - requests
  - snakemake
  - pip
  - pip:
      - sentence-transformers
